<?php

$title = $this->translate('Login');
$this->headMeta()->appendName('keywords', 'Sign In, Login, Authenticate');
$this->headMeta()->appendName('description', 'Login to my account');
$this->headTitle($this->escapeHtml($title));

$form = $this->form;
$form->setAttribute('action', $this->url('login'));
$form->prepare();
?>

<div class="container">
    <div class="row">
        <div class="col-md-4 shadow-sm">
            <h3 class="md-3 pt-2 text-md-center">
                <?= $this->escapeHtml($this->translate('Login')); ?>
            </h3>

            <?= $this->form()->openTag($form); ?>

            <span class="form-text text-muted pb-2">
                  <?= sprintf(
                      $this->translate('Dont have an account? %sCreate account%s'),
                      '<a href="'.$this->url('register').'">', '</a>'
                  ); ?>
            </span>
            <div class="mb-3">
                <?= $this->formLabel($form->get('email')); ?>
                <div class="form-group">
                    <?= $this->formText($form->get('email')); ?>
                </div>
                <div class="text-danger">
                    <?= $this->formElementErrors($form->get('email')) ;?>
                </div>
            </div>
            <div class="mb-3">
                <?= $this->formLabel($form->get('password')); ?>
                <div class="form-group">
                    <?= $this->formText($form->get('password')); ?>
                </div>
                <div class="text-danger">
                    <?= $this->formElementErrors($form->get('password')) ;?>
                </div>
            </div>
            <div class="mb-3">
                <div class="custom-control custom-checkbox">
                    <?= $this->formCheckbox($form->get('recall')); ?>
                    <?= $this->formLabel($form->get('recall')); ?>
                </div>
            </div>
            <div class="mb-3 float-right">
                <?= $this->formHidden($form->get('csrf')); ?>
                <div class="text-danger">
                    <?= $this->formElementErrors($form->get('csrf')) ;?>
                </div>
                <?= $this->formSubmit($form->get('account_login')) ;?>
            </div>
            <?= $this->form()->closeTag(); ;?>
        </div>
    </div>
</div>