<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>
<?= $this->doctype() ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('Laminas MVC Skeleton')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink([
                                'rel' => 'shortcut icon',
                                'type' => 'image/vnd.microsoft.icon',
                                'href' => $this->basePath() . '/img/favicon.ico'
                            ])
            ->prependStylesheet($this->basePath('css/app.css'))
            ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
?>

        <!-- Scripts -->
        <?= $this->headScript() ?>
    </head>
    <body>
        <div class="container">
            <header class="brand-header py-3">
                <div class="row flex-nowrap justify-content-between align-items-center">
                    <div class="col-4 pt-1">
                        <?= date('l, j, F, Y'); ?>
                    </div>
                    <div class="logo col-4 text-center">
                        <a href="<?= $this->url('home'); ?>">Quiz</a>
                    </div>
                    <div class="col-4 d-flex justify-content-end align-items-center">
                        <a href="<?= $this->url('login'); ?>" class="btn btn-sm
                        btn-outline-secondary">
                            Login
                        </a>
                        <a href="<?= $this->url('register'); ?>" class="btn btn-sm
                        btn-outline-secondary">
                            Register
                        </a>
                    </div>
                </div>
            </header>
            <div class="appNavigation py-1 mb-2">
                <nav class="nav d-flex justify-content-between">
                    <a href="<?= $this->url('home'); ?>" class="pt-2 text-muted">
                        Home
                    </a>
                    <a href="<?= $this->url('home'); ?>" class="pt-2 text-muted">
                        Members
                    </a>
                </nav>
            </div>
        </div>
        <main class="container" role="main">
            <?= $this->partial('flushMessages/flash.phtml', $this->flashMessenger()) ?>
            <?= $this->content ?>
            <hr>
        </main>
        <footer class="text-center text-muted">
            <p>
                &copy; <?= date('Y') ?>
                Quiz
            </p>
        </footer>
        <?= $this->inlineScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery-3.5.1.min.js')) ?>
    </body>
</html>
